version: '3.9'
services:
  postgres:
    container_name: spring-boot-postgres
    image: postgres:15.1-alpine3.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: #@Postgres.Com0107
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: